FROM python:3.11-slim
WORKDIR /app
RUN pip install streamlit requests plotly pandas
COPY frontend/ ./frontend/
EXPOSE 8501
CMD ["streamlit", "run", "frontend/app.py","--server.address", "0.0.0.0", "--server.port", "8501"]
